// src/components/RecipeForm.jsx (top)
const AVAILABLE_UNITS = [
      { value: "", label: { en: "-- Select unit --", ar: "— اختر الوحدة —" } },
      { value: "mg", label: { en: "milligram (mg)", ar: "مليغرام (ملغ)" } },
      { value: "g", label: { en: "gram (g)", ar: "غرام (غ)" } },
      { value: "kg", label: { en: "kilogram (kg)", ar: "كيلوغرام (كغ)" } },
      { value: "oz", label: { en: "ounce (oz)", ar: "أوقية (أوز)" } },
      { value: "lb", label: { en: "pound (lb)", ar: "رطل (رطل)" } },

      { value: "ml", label: { en: "milliliter (ml)", ar: "مليلتر (مل)" } },
      { value: "l", label: { en: "liter (l)", ar: "لتر (ل)" } },
      { value: "tsp", label: { en: "teaspoon (tsp)", ar: "ملعقة صغيرة" } },
      { value: "tbsp", label: { en: "tablespoon (tbsp)", ar: "ملعقة كبيرة" } },
      { value: "fl oz", label: { en: "fluid ounce (fl oz)", ar: "أونصة سائلة" } },
      { value: "cup", label: { en: "cup", ar: "كوب" } },
      { value: "pint", label: { en: "pint", ar: "باينت" } },
      { value: "quart", label: { en: "quart", ar: "كوارت" } },
      { value: "gal", label: { en: "gallon", ar: "غالون" } },

      { value: "count", label: { en: "count", ar: "عدد" } },
      { value: "unit", label: { en: "unit", ar: "وحدة" } },
      { value: "small", label: { en: "small", ar: "صغير" } },
      { value: "medium", label: { en: "medium", ar: "متوسط" } },
      { value: "large", label: { en: "large", ar: "كبير" } },
      { value: "extra large", label: { en: "extra large", ar: "كبير جدًا" } },

      { value: "piece", label: { en: "piece", ar: "قطعة" } },
      { value: "slice", label: { en: "slice", ar: "شريحة" } },
      { value: "clove", label: { en: "clove", ar: "فص" } },
      { value: "can", label: { en: "can", ar: "علبة" } },
      { value: "bottle", label: { en: "bottle", ar: "زجاجة" } },
      { value: "jar", label: { en: "jar", ar: "مرطبان" } },
      { value: "package", label: { en: "package", ar: "عبوة" } },
      { value: "box", label: { en: "box", ar: "صندوق" } },
      { value: "stick", label: { en: "stick", ar: "عود" } },
      { value: "bunch", label: { en: "bunch", ar: "ربطة" } },
      { value: "sprig", label: { en: "sprig", ar: "غصن" } },
      { value: "head", label: { en: "head", ar: "رأس" } },
      { value: "leaf", label: { en: "leaf", ar: "ورقة" } },
      { value: "ear", label: { en: "ear", ar: "سنبل" } },
      { value: "fillet", label: { en: "fillet", ar: "فيليه" } },
      { value: "handful", label: { en: "handful", ar: "حفنة" } },
      { value: "pinch", label: { en: "pinch", ar: "رشة" } },
      { value: "dash", label: { en: "dash", ar: "رشّة صغيرة" } },

      { value: "serving", label: { en: "serving", ar: "حصة" } },
      { value: "scoop", label: { en: "scoop", ar: "مغرفة" } },
      { value: "shot", label: { en: "shot", ar: "شوت" } },
      { value: "bar", label: { en: "bar", ar: "قالب" } },

      { value: "roll", label: { en: "roll", ar: "لفافة" } },
      { value: "sheet", label: { en: "sheet", ar: "ورقة" } },
      { value: "cube", label: { en: "cube", ar: "مكعب" } },
      { value: "envelope", label: { en: "envelope", ar: "ظرف" } },
      { value: "bag", label: { en: "bag", ar: "كيس" } },
      { value: "package yield", label: { en: "package yield", ar: "كمية العبوة" } },
      { value: "inch", label: { en: "inch", ar: "بوصة" } },
      { value: "cm", label: { en: "centimeter", ar: "سنتيمتر" } },
      { value: "slice-equivalent", label: { en: "slice-equivalent", ar: "ما يعادل شريحة" } },
      { value: "sprinkle", label: { en: "sprinkle", ar: "رشة" } },

      { value: "log", label: { en: "log", ar: "لفافة" } },
      { value: "wedge", label: { en: "wedge", ar: "مثلث" } },
      { value: "stick-equivalent", label: { en: "stick-equivalent", ar: "ما يعادل عود" } },
      { value: "pat", label: { en: "pat", ar: "قطعة زبدة" } },

      { value: "rib", label: { en: "rib", ar: "ضلوع" } },
      { value: "drumstick", label: { en: "drumstick", ar: "فخذ" } },
      { value: "thigh", label: { en: "thigh", ar: "فخذ" } },
      { value: "wing", label: { en: "wing", ar: "جناح" } },
      { value: "leg", label: { en: "leg", ar: "ساق" } },
      { value: "breast", label: { en: "breast", ar: "صدر" } },
      { value: "loin", label: { en: "loin", ar: "متن" } },
      { value: "chop", label: { en: "chop", ar: "قطعة لحم" } },
      { value: "steak", label: { en: "steak", ar: "شريحة لحم" } },

      { value: "drop", label: { en: "drop", ar: "قطرة" } },
      { value: "packet", label: { en: "packet", ar: "رزمة" } },
      { value: "ladle", label: { en: "ladle", ar: "مغرفة" } },
      { value: "ring", label: { en: "ring", ar: "حلقة" } },
      { value: "ball", label: { en: "ball", ar: "كرة" } },
      { value: "chunk", label: { en: "chunk", ar: "قطعة" } },
      { value: "container", label: { en: "container", ar: "حاوية" } },
      { value: "tube", label: { en: "tube", ar: "أنبوب" } },
      { value: "pouch", label: { en: "pouch", ar: "كيس صغير" } },
      { value: "whole", label: { en: "whole", ar: "كامل" } }
];



// language‑aware maps
const unitMapEn = {
      mg: "mg", milligram: "mg", milligrams: "mg",
      g: "g", gram: "g", grams: "g",
      kg: "kg", kilogram: "kg", kilograms: "kg",
      oz: "oz", ounce: "oz", ounces: "oz",
      lb: "lb", pound: "lb", pounds: "lb",

      ml: "ml", milliliter: "ml", milliliters: "ml",
      l: "l", liter: "l", liters: "l",
      tsp: "tsp", teaspoon: "tsp", teaspoons: "tsp",
      tbsp: "tbsp", tablespoon: "tbsp", tablespoons: "tbsp",
      "fl oz": "fl oz", "fluid ounce": "fl oz", "fluid ounces": "fl oz",
      cup: "cup", cups: "cup",
      pint: "pint", pints: "pint",
      quart: "quart", quarts: "quart",
      gal: "gal", gallon: "gal", gallons: "gal",

      count: "count", unit: "unit", units: "unit",
      small: "small", medium: "medium", large: "large", "extra large": "extra large",

      piece: "piece", pieces: "piece",
      slice: "slice", slices: "slice",
      clove: "clove", cloves: "clove",
      can: "can", cans: "can",
      bottle: "bottle", bottles: "bottle",
      jar: "jar", jars: "jar",
      package: "package", packages: "package",
      box: "box", boxes: "box",
      stick: "stick", sticks: "stick",
      bunch: "bunch", bunches: "bunch",
      sprig: "sprig", sprigs: "sprig",
      head: "head", heads: "head",
      leaf: "leaf", leaves: "leaf",
      ear: "ear", ears: "ear",
      fillet: "fillet", fillets: "fillet",
      handful: "handful", handfuls: "handful",
      pinch: "pinch", pinches: "pinch",
      dash: "dash", dashes: "dash",

      serving: "serving", servings: "serving",
      scoop: "scoop", scoops: "scoop",
      shot: "shot", shots: "shot",
      bar: "bar", bars: "bar",

      roll: "roll", rolls: "roll",
      sheet: "sheet", sheets: "sheet",
      cube: "cube", cubes: "cube",
      envelope: "envelope", envelopes: "envelope",
      bag: "bag", bags: "bag",
      "package yield": "package yield",
      inch: "inch", inches: "inch",
      cm: "cm", centimeter: "cm", centimeters: "cm",
      "slice-equivalent": "slice-equivalent",
      sprinkle: "sprinkle", sprinkles: "sprinkle",

      log: "log", logs: "log",
      wedge: "wedge", wedges: "wedge",
      "stick-equivalent": "stick-equivalent",
      pat: "pat", pats: "pat",

      rib: "rib", ribs: "rib",
      drumstick: "drumstick", drumsticks: "drumstick",
      thigh: "thigh", thighs: "thigh",
      wing: "wing", wings: "wing",
      leg: "leg", legs: "leg",
      breast: "breast", breasts: "breast",
      loin: "loin", loins: "loin",
      chop: "chop", chops: "chop",
      steak: "steak", steaks: "steak",

      drop: "drop", drops: "drop",
      packet: "packet", packets: "packet",
      ladle: "ladle", ladles: "ladle",
      ring: "ring", rings: "ring",
      ball: "ball", balls: "ball",
      chunk: "chunk", chunks: "chunk",
      container: "container", containers: "container",
      tube: "tube", tubes: "tube",
      pouch: "pouch", pouches: "pouch",
      whole: "whole", wholes: "whole"
};


const unitMapAr = {
      ملغ: "mg", مليغرام: "mg", مليغرامات: "mg",
      غرام: "g", غرامات: "g",
      كغ: "kg", كيلوغرام: "kg", كيلوغرامات: "kg",
      أوقية: "oz", أوقيات: "oz",
      رطل: "lb", أرطال: "lb",

      مل: "ml", مليلتر: "ml", مليلترات: "ml",
      ل: "l", لتر: "l", لترات: "l",
      "ملعقة صغيرة": "tsp",
      "ملعقة صغيرة جدًا": "tsp",
      "ملعقة كبيرة": "tbsp",
      "أونصة سائلة": "fl oz",
      كوب: "cup", أكواب: "cup",
      باينت: "pint", باينتات: "pint",
      كوارت: "quart", كوارتات: "quart",
      غالون: "gal", غالونات: "gal",

      عدد: "count",
      وحدة: "unit", وحدات: "unit",
      صغير: "small",
      متوسط: "medium",
      كبير: "large",
      "كبير جدًا": "extra large",

      قطعة: "piece", قطع: "piece",
      شريحة: "slice", شرائح: "slice",
      فص: "clove", فصوص: "clove",
      علبة: "can", علب: "can",
      زجاجة: "bottle", زجاجات: "bottle",
      مرطبان: "jar", مرطبانات: "jar",
      عبوة: "package", عبوات: "package",
      صندوق: "box", صناديق: "box",
      عود: "stick", أعواد: "stick",
      ربطة: "bunch", ربطات: "bunch",
      غصن: "sprig", أغصان: "sprig",
      رأس: "head", رؤوس: "head",
      ورقة: "leaf", أوراق: "leaf",
      سنبل: "ear", سنابل: "ear",
      فيليه: "fillet", فيليهات: "fillet",
      حفنة: "handful", حفنات: "handful",
      رشة: "pinch", رشات: "pinch",
      "رشّة صغيرة": "dash", رشة_صغيرة: "dash",

      حصة: "serving", حصص: "serving",
      مغرفة: "scoop", مغارف: "scoop",
      شوت: "shot", شوتات: "shot",
      قالب: "bar", قوالب: "bar",

      لفافة: "roll", لفافات: "roll",
      ورقة: "sheet", أوراق: "sheet",
      مكعب: "cube", مكعبات: "cube",
      ظرف: "envelope", ظروف: "envelope",
      كيس: "bag", أكياس: "bag",
      "كمية العبوة": "package yield",
      بوصة: "inch", بوصات: "inch",
      سنتيمتر: "cm", سنتيمترات: "cm",
      "ما يعادل شريحة": "slice-equivalent",
      رشّة: "sprinkle", رشّات: "sprinkle",

      مثلث: "wedge", مثلثات: "wedge",
      "ما يعادل عود": "stick-equivalent",
      "قطعة زبدة": "pat", قطع_زبدة: "pat",

      ضلوع: "rib", ضلع: "rib",
      فخذ: "thigh", أفخاذ: "thigh",
      جناح: "wing", أجنحة: "wing",
      ساق: "leg", سيقان: "leg",
      صدر: "breast", صدور: "breast",
      متن: "loin", متون: "loin",
      "قطعة لحم": "chop", قطع_لحم: "chop",
      "شريحة لحم": "steak", شرائح_لحم: "steak",

      قطرة: "drop", قطرات: "drop",
      رزمة: "packet", رزم: "packet",
      مغرفة: "ladle", مغارف: "ladle",
      حلقة: "ring", حلقات: "ring",
      كرة: "ball", كرات: "ball",
      قطعة: "chunk", قطع: "chunk",
      حاوية: "container", حاويات: "container",
      أنبوب: "tube", أنابيب: "tube",
      "كيس صغير": "pouch", أكياس_صغيرة: "pouch",
      كامل: "whole", كمال: "whole"
};


const translations = {
      title: { en: "Recipe Title", ar: "عنوان الوصفة" },
      description: { en: "Description", ar: "الوصف" },
      ingredientName: { en: "Ingredient Name", ar: "اسم المكون" },
      addIngredient: { en: "Add Ingredient", ar: "إضافة مكون" },
      removeIngredient: { en: "Remove Ingredient", ar: "إزالة المكون" },
      instructions: { en: "Instructions", ar: "خطوات التحضير" },
      addStep: { en: "Add Step", ar: "إضافة خطوة" },
      stepImage: { en: "Step Image", ar: "صورة الخطوة" },
      stepDetails: { en: "Instructions", ar: "التفاصيل" },
      describeStep: { en: "Describe the step...", ar: "وصف الخطوة..." },
      prepTime: { en: "Preparation Time", ar: "وقت التحضير" },
      servings: { en: "Servings", ar: "عدد الحصص" },
      thumbnail: { en: "Thumbnail Image", ar: "الصورة المصغرة" },
      uploadThumbnail: { en: "Click to upload thumbnail", ar: "انقر لرفع الصورة المصغرة" },
      otherImages: { en: "Additional Images", ar: "صور إضافية" },
      uploadAdditional: { en: "Click to upload additional images", ar: "انقر لرفع صور إضافية" },
      saveRecipe: { en: "Saving...", ar: "جارٍ الحفظ..." },
      createRecipe: { en: "Create Recipe", ar: "إنشاء الوصفة" },
      updateRecipe: { en: "Update Recipe", ar: "تحديث الوصفة" },
      required: { en: "Required", ar: "مطلوب" },
      unit: { en: "Unit", ar: "الوحدة" },
      quantity: { en: "Quantity", ar: "الكمية" },
};



export {
      AVAILABLE_UNITS,
      unitMapEn,
      unitMapAr,
      translations
}